
image: Visual Studio 2017
platform: x64
version: 1.0.{build}

build_script:
  - cd build
  - mkdir win64
  - cd win64
  - dir "C:/Program Files/LLVM/bin"
  - dir "C:/Program Files/LLVM/include"
  - dir "C:/Program Files/LLVM/lib"
  - dir "C:/Program Files/LLVM/libexec"
  - dir "C:/Program Files/LLVM/shared"
#  - cmake -DUSE_LLVM_CONFIG=off -DLLVM_DIR="C:/Program Files/LLVM/lib/cmake/llvm" -C ../backends/most.cmake -C ../targets/regular.cmake .. -G "Visual Studio 15 2017 Win64"
#  - cmake --build . --config Release
#  - ls -l ../bin/Release

notifications:
  - provider: Email
    to:
      - '{{commitAuthorEmail}}'
      - orlarey@grame.fr
    subject: 'Build {{status}}: {{projectName}} {{buildVersion}}'
    on_build_success: false
    on_build_failure: true
    on_build_status_changed: true
