
image: Visual Studio 2017
platform: x64
version: 1.0.{build}

build_script:
  - cd build
  - mkdir win64
  - cd win64
  - cmake -C ../backends/regular.cmake -C ../targets/regular.cmake .. -G "Visual Studio 17 2022"
  - cmake --build . --config Release
  - ls -l ../bin/Release

notifications:
  - provider: Email
    to:
      - '{{commitAuthorEmail}}'
      - orlarey@grame.fr
    subject: 'Build {{status}}: {{projectName}} {{buildVersion}}'
    on_build_success: false
    on_build_failure: true
    on_build_status_changed: true
